// Elenchus GUI - HTML Tab Content
//
// Renders self-contained HTML content (e.g. context dumps) inside a sandboxed iframe.
// Uses srcdoc to inject the HTML directly — no file:// URL or network request needed.
//
// ## Security
// The HTML is generated by the main process (formatContextAsHtml), so it is trusted.
// The iframe uses sandbox="" to prevent any scripts within the HTML from accessing
// the parent application, while still allowing CSS styling to work.
//
// ## Keep-Alive Contract
// Same as other tab content components — does NOT receive isActive.

import React from "react";
import type { TabContentProps } from "./tab-types";

export const HtmlTabContent = React.memo(function HtmlTabContent({ content }: TabContentProps) {
  if (!content) return null;

  return (
    <iframe
      srcDoc={content.content}
      sandbox=""
      className="html-tab-iframe"
      title="Context dump"
    />
  );
});
